# Generated by Django 4.0.4 on 2022-05-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submit',
            name='id',
            field=models.IntegerField(blank=b'I00\n', primary_key=True, serialize=False),
        ),
    ]
