# Generated by Django 4.0.4 on 2022-05-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_progress_id_alter_submit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='problem_id',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='progress',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='problem_id_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
